[build]
builder = "nixpacks"
buildCommand = "npm run build && npx prisma migrate deploy"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

[[volumes]]
name = "sqlite_data"
mountPath = "/app/data"
